### ISSUE TITLE
Quarto not rendering rmarkdown HTML since knitr update

### ISSUE THREAD

**Issue by brainprint** [quarto-dev/quarto-r#109]
Hi,

I have a Quarto file that I update regularly. Since today, I am not able to render it. 

I have read some post regarding uninstall/install xfun, but it didn't work.

**Today** I have updated **knitr** package and I believe it could be related. The problem is connected to a plotly chart. When I try to run/render each chunk separately I get the right charts.

I would appreciate any help you could offer.

Best, B.

The error is:

Quitting from lines 74-75 [unnamed-chunk-2] (xxxYYY.qmd)
Error in `add_html_caption()`:
! unused argument (xfun::grep_sub("^[^<]*<[^>]+aria-labelledby[ ]*=[ ]*\"([^\"]+)\".*$", "\\1", x))
Backtrace:
  1. global .main()
  2. execute(...)
  3. rmarkdown::render(...)
  4. knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  5. knitr:::process_file(text, output)
     ...
 14. sew(res, options)
 15. knitr:::sew.list(x, options, ...)
 16. base::lapply(x, sew, options, ...)
 17. FUN(X[[i]], ...)
 18. knitr:::sew.knit_asis(x, options, ...)
Execution halted

R version 4.3.0 (2023-04-21)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Amsterdam
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.0  tools_4.3.0     rstudioapi_0.14

**Comment by cderv** [comment]
Thanks. this is a known issue tracked at 
* https://github.com/quarto-dev/quarto-cli/issues/5702 
* https://github.com/yihui/knitr/issues/2261

For now you need to revert knitr version to 1.42. Sorry for the trouble

**Comment by brainprint** [comment]
No problems. Thank you very much for the prompt answer.
