### ISSUE TITLE
Problems Rendering in R

### ISSUE THREAD

**Issue by AtomicNess123** [quarto-dev/quarto-r#11]
I followed the isntructions: downloaded last RStudio version and sample QMD document. 
I click on Render, but nothing happens. Is there any package I should install?

**Comment by cderv** [comment]
The only thing to do is follow the instruction in Quarto documentation: https://quarto.org/docs/get-started/hello/rstudio.html

This R package, which is this repo, is not necessary. Main CLI tools live in [quarto-dev/quarto-cli](https://github.com/quarto-dev/quarto-cli)

If you still have issue, please share your RStudio version and what happens exactly in your session. 

Thank you
