### ISSUE TITLE
With a revealjs format, is there a way to reference images outside the .qmd file's directory?

### ISSUE THREAD

**Issue by lytello** [quarto-dev/quarto-r#110]
I have tried several relative paths from my .qmd file to no avail:

`/figures/images.svg`
`figures/image.svg`
`../figures/image.svg`

**Comment by cderv** [comment]
Can you provide a full reproducible example ? A project with the files that you could share as a github repo maybe ? 

This would help us know the context of your work. Passing some image from a subfolder of your working space should work fine. 

Thank you
