### ISSUE TITLE
quarto::quarto_publish_doc fails

### ISSUE THREAD

**Issue by csgillespie** [quarto-dev/quarto-r#118]
I've been publishing quarto docs for a while, but this now fails.

Publishing to the server now gives this error
```
Error in `rsconnect::deployApp()`:
! `appFiles` must be a character vector or `NULL`, not a list.
```
This is due to the following lines in `quarto::quarto_publish_doc()`

```
inspect <- quarto:::quarto_inspect(input)
resources <- inspect[["resources"]]
app_files <- unique(c(app_files, resources))
```
The object `resources` is an empty list. Running `quarto inspect index.qmd` in a terminal, the output JSON shows that `resources` is empty as well. 

I can make a fix, but I'm not sure why I __now__ get this error.

----

 * R 4.2.1
 *  {quarto} 1.2
 *  {jsonlite} 1.8.7
 * quarto 1.3.450
Document (index.qmd)

```
---
title: "Habits"
author: "John Doe"
format: beamer
---

## Getting up

- Turn off alarm
- Get out of bed

## Going to sleep

- Get in bed
- Count sheep

```

**Comment by thomascwells** [comment]
I encountered what I think is the same error. It seems like upgrading to {quarto} 1.3 fixed this for me. 1.3 was published to CRAN just a couple days ago.

**Comment by cderv** [comment]
It seems indeed to be working now... 

@csgillespie do you still have the issue ?

**Comment by csgillespie** [comment]
Upgrading fixed the issue
