### ISSUE TITLE
Links in "Other formats" point to root, even if `.qmd` and outputs are in a subfolder

### ISSUE THREAD

**Issue by CeresBarros** [quarto-dev/quarto-r#121]
I have an R Studio project (and GitHub repo) that contains several subfolders with quarto documents that I render in HTML and PDF formats. All seems to be well and both the HTML and PDF outputs are rendered to the directory where the `.qmd` file lives (let's call it `proj/documentFolder/` and the files end up in `proj/documentFolder/document.html` and `proj/documentFolder/document.pdf`). 

However the link to the PDF showing in "Other formats" (on the HTML) points to the root RStudio project directory (`proj/` above), instead of the subfolder where the PDF was rendered to (`proj/documentFolder`).

Is there a way of 1) changing this link or 2) rendering the PDF to the parent directory?
I would prefer no. 1 as having the PDF on the parent directory breaks my file organisation.

Thanks!

**Comment by cderv** [comment]
Thanks for the report. Please when you open an issue, do try to share a reproducible example. This way we can quickly check if we can reproduce, and look into the issue. 

When you are not sharing it, we need to spend time understand and make one, or sometime we just wait for a reproducible to fix something. 

Here is an example of things you could share: 

````
quarto create project default proj
cd proj
mkdir documentFolder
cd documentFolder
````

Create and edit `document.qmd` with your favorite editor
````markdown
---
title: document
format:
  html: default
  pdf: default
---

# Content
````

Then go back in the project
````
cd ..
````

And run `quarto preview .\documentFolder\document.qmd` : The link will be ok 
![image](https://github.com/quarto-dev/quarto-r/assets/6791940/bf35cd2b-b6a3-4edb-a440-c015320a155b)

If I click on the link the PDF document opens.

**Comment by CeresBarros** [comment]
You're absolutely right. Apologies.
I wasn't quite sure how to provide a reprex for this and yours doesn't reflect my situation (likely because I haven't explained it v. well). 
However, your tips helped me figure out the problem!

It seems that the link to the PDF will point to the directory from where the `.qmd` was _rendered_, rather than where it is _located_. It would be great if this was documented somewhere (maybe in the [Other Formats section](https://quarto.org/docs/output-formats/html-multi-format.html)) so that others don't spend as much time trying to figure out what's wrong.

Reprex:
```
mkdir -p proj/documentFolder
vi documentFolder/document.qmd 
```
copy-paste:
```
---
title: document
format:
  html: default
  pdf: default
---

## content
```

render from parent directory
```
quarto render documentFolder/document.qmd
```
On the bottom of the figure you see that the PDF link is pointing to `proj/document.pdf`, which does not exist. 
![image](https://github.com/quarto-dev/quarto-r/assets/22214224/82fd4294-0dff-4cc5-9981-3e1e0c6d7abb)

However if we go to the `documentFolder` directory and _then_ tender from there, the link is correct
```
cd documentFolder
quarto render document.qmd
```
![image](https://github.com/quarto-dev/quarto-r/assets/22214224/e05fa274-4373-489a-9ea5-9587de629899)

**Comment by cderv** [comment]
@CeresBarros in both your example, you should look at the HTML file content. In both case I see 
````html
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="document.pdf"><i class="bi
bi-file-pdf"></i>PDF</a></li></ul></div></div>
````

Meaning the link created is  `<a href="document.pdf">`. In HTML world this is relative link for [file paths](https://www.w3schools.com/html/html_filepaths.asp). It means that `document.pdf` will be referencing a file at the same place that the HTML file. 

Try using `quarto preview` to open you page in a web server and see how it behaves. 

Hope it helps
