### ISSUE TITLE
Rebuild pkgdown site for version 1.3

### ISSUE THREAD

**Issue by remlapmot** [quarto-dev/quarto-r#122]
I noticed that the pkgdown site is still for version 1.2 <https://quarto-dev.github.io/quarto-r/>

<img width="428" alt="Screenshot 2023-09-21 at 19 11 37" src="https://github.com/quarto-dev/quarto-r/assets/3777473/027d59c3-52bd-4d52-b48d-ff12b6cbbf75">

**Comment by cderv** [comment]
Thanks ! This is updated now with https://github.com/quarto-dev/quarto-r/commit/dbbd4a7018fc6d1e04b56ff1218e89ef18abcf58

@jjallaire **pkgdown** website is now automatically build from main.
