### ISSUE TITLE
Rendering website/book from R console

### ISSUE THREAD

**Issue by royfrancis** [quarto-dev/quarto-r#15]
I am working on a quarto *book* project.

```
project:
  type: book
```

The [guide](https://quarto.org/docs/books/#rstudio) suggests **Render Book** command on the **Build** tab. This works, but what's the equivalent command to build from the R console? I am thinking of something similar to `rmarkdown::build_site()`?

**Comment by cderv** [comment]
We have made a Quarto R package that you'll find on CRAN: https://cran.r-project.org/web/packages/quarto/index.html

Repo is here: https://github.com/quarto-dev/quarto-r

It will allow you to call `quarto` CLI from R console.

**Comment by cderv** [comment]
For reference `quarto_render()` is the function to use.
