### ISSUE TITLE
Add Quarto Pub option to quarto_publish_doc() and quarto_publish_site()

### ISSUE THREAD

**Issue by davidkane9** [quarto-dev/quarto-r#177]
The [help page](https://quarto-dev.github.io/quarto-r/reference/quarto_publish_doc.html) for quarto_publish_doc and friends specifies that:

> Publish Quarto documents to Posit Connect, ShinyApps, and RPubs

It would be helpful if these functions also allowed us to publish to Quarto Pub. My specific use case is helping beginner students to put a [Quarto website on the the web](https://bootcamp.davidkane.info/projects.html), for all to see for free. Posit Connect costs money while ShinyApps and RPubs do not handle websites. So, I think my only option is to show students how to use Quarto CLI, which is tough for beginners.

**Comment by cderv** [comment]
This will be done by wrapping the `quarto publish` command. 

- https://github.com/quarto-dev/quarto-r/issues/101

**rsconnect** package is also now the recommended way to publish to Posit Connect, Posit Cloud and ShinyApps.io 

We'll soon deprecate those functions 
- #102 

So options will be

- **rsconnect** for some providers
- `quarto publish` command (and the wrapper that will be available in this package soon) as other options (like Quarto Pub). 

It is the same team working on both Quarto R package, and Quarto CLI and so work need to be split, and priority is just right now on the CLI. I'll do an update of Quarto R probably after next CLI update.

**Comment by cderv** [comment]
Just to be clear, I am closing because of the two linked issue existing already. 

> So, I think my only option is to show students how to use Quarto CLI, which is tough for beginners.

Posit Cloud is another option that is available through **rsconnect** package in the meantime if this helps to have an R wrapper. But it requires a Posit Cloud account I guess.
