### ISSUE TITLE
Return generated files from `quarto_render()`

### ISSUE THREAD

**Issue by hadley** [quarto-dev/quarto-r#183]
This would be useful when you're building a directory of files

**Comment by cderv** [comment]
So when you pass a directory to `quarto_render`, to return all the files generated from the directory ? 

Using CLI, I don't think we have this information directly, so it would need to be computed (probably with `quarto inspect`). 🤔

**Comment by hadley** [comment]
Ah if you don't have it directly, it's probably not worth worrying about. Also I no longer need this since I'm using an empty output dir, I can just list the contents of that directory.
