### ISSUE TITLE
Mathematical notation in quarto::html vignettes

### ISSUE THREAD

**Issue by zeileis** [quarto-dev/quarto-r#193]
Christophe @cderv, thanks for the chat today at useR!. As you advised I'm quickly writing up problem and solution in this issue:

In `quarto::html` vignettes mathematical rendering seems to be disabled by default (using R/`quarto` 1.4 and  `quarto` 1.5.53).

Enabling again can be done via `html-math-method`, e.g.,

```
format: 
  html:
    html-math-method: mathjax
```

**Comment by cderv** [comment]
Thanks. It seems the `theme: none` for vignette is deactivating the default math (that should have been `mathjax`). 

This is new to me but maybe not an issue per-se. I should document it, with the way to opt-in again if needed.

**Comment by zeileis** [comment]
Christophe, thanks for the feedback. I agree that improving the documentation would be sufficient for this. I propose some small additions for the `hello.qmd` vignette in PR https://github.com/quarto-dev/quarto-r/pull/195
