### ISSUE TITLE
Is it possible to use/port R Markdown templates within Quarto? 

### ISSUE THREAD

**Issue by harrylojames** [quarto-dev/quarto-r#21]
I have a number of custom RMarkdown templates for rendering HTML. I would like to know if I can use these for Quarto.

**Comment by cderv** [comment]
Are the R Markdown templates you are mentioning Pandoc's HTML template (e.g `template.html`) or custom format for R Markdown to pass in `output:` (e.g `output: mypkg::custom_format()` ) ? 
Or are you talking about R Markdown template `.Rmd` file stored in packages ? (i.e https://bookdown.org/yihui/rmarkdown-cookbook/package-template.html) 

How are you custom R Markdown templates built ? How are you using them today ? 

I am just asking for clarification to be sure we are talking about the same thing.

You probably won't be able to use them as this though as Quarto and R Markdown have some differences, but depending on the template type it would be easy to port to be used with Quarto ? 

 Based on you additional information, I'll may be able to provide more insights on what is supported and could be done

**Comment by cderv** [comment]
Custom format for R Markdown are R functions and can only be used with R Markdown. They won't work with Quarto. 

Authors of custom formats would need to port them to Quarto extensions format.
