### ISSUE TITLE
DiagrammeR::grViz() in chunk not working in new versions of Quarto

### ISSUE THREAD

**Issue by asadow** [quarto-dev/quarto-r#218]
After updating Quarto and rendering my .qmd, I got this error output instead of the diagram: `TypeError: Assignment to constant variable.`

I had to downgrade back to 1.3.450 to fix it.

![Image](https://github.com/user-attachments/assets/310986ae-97c0-4903-8e2b-744fe887001c)

**Comment by asadow** [comment]
E.g.

```
```{r}
DiagrammeR::grViz("digraph {

graph [layout = dot, rankdir = LR]
node [shape = rectangle, style = filled, fillcolor = Linen]
owner [label = 'Owner', shape = circle]

}")
```
```

**Comment by cderv** [comment]
How do you render ? Which quarto version to you have ? Which version of the R package . 

I can't reproduce 
````markdown
---
title: Test
keep-md: true
---

```{r}
DiagrammeR::grViz("digraph {

graph [layout = dot, rankdir = LR]
node [shape = rectangle, style = filled, fillcolor = Linen]
owner [label = 'Owner', shape = circle]

}")

```
````

![Image](https://github.com/user-attachments/assets/37239aab-b266-4a6f-859c-b3d21811b593)

I used latest pre-release Quarto 1.6.37, with R 4.4.2 and those packages versions 
````
> lapply(c("knitr", "rmarkdown", "DiagrammeR"), packageVersion, )
[[1]]
[1] ‘1.49’

[[2]]
[1] ‘2.29’

[[3]]
[1] ‘1.0.11’
````

**Comment by cderv** [comment]
If it does not work for you, then we need to find why. So don't hesitate to reopen and share more information.

**Comment by dchiu911** [comment]
Phenomenon explained [here](https://github.com/rich-iannone/DiagrammeR/issues/519#issuecomment-1959744895). So does that mean quarto is not able to preview a grviz image?

**Comment by cderv** [comment]
It seems to be a conflict with `quarto preview` logic and `viz.js` used in DiagrammeR. Let's discussin in 
- https://github.com/rich-iannone/DiagrammeR/issues/519#issuecomment-1959744895
