### ISSUE TITLE
Feature Request - Quarto Update and Rstudio

### ISSUE THREAD

**Issue by sammo3182** [quarto-dev/quarto-r#23]
Updating Quarto through R codes and auto setup the path can be helpful. I found when installing quarto separately as the Website suggests, Rstudio would not recognize that automatically. I installed the developed version in Linux Ubuntu as the [README](https://github.com/quarto-dev/quarto-cli) instructed and got this back in the terminal

````
$ quarto --version
99.9.9
````

But Rstudio still only recognized the old version:

``` r
> quarto::quarto_path()
[1] "/usr/local/bin/quarto"
> quarto::quarto_version()
[1] ‘0.9.640’
```

The same issue happened when I installed a stable version in Windows. I know it is probably again the path issue, although the path in Linux looks right. Anyway, a function that can update Quarto and set the path right would make quarto more user-friendly.

**Comment by cderv** [comment]
The Quarto R package will find `quarto` available on PATH or set explicitly through `QUARTO_PATH`. 

So probably here `quarto::quarto_path()` returns to you one for these two.
