### ISSUE TITLE
Conflicts between R chunks, `output-file`, and `_quarto.yml`

### ISSUE THREAD

**Issue by MCMaurer** [quarto-dev/quarto-r#32]
I am trying to render a `README.md` file from a Quarto file, but due to the bug mentioned [here](https://github.com/quarto-dev/quarto-cli/issues/1615), I have to call the Quarto doc `read_me.qmd` and use `output-file: "README"` in the header. 

However, this seems to cause some problems, particularly with the interaction of the `output-file` flag, R chunks in the Quarto doc, and the presence of a `_quarto.yml` file.

If there is an `output-file` set, the Quarto doc contains an R chunk, and there is a `_quarto.yml` file in the directory, the following error occurs:

```
processing file: read_me.qmd
  |.......................                                               |  33%
  ordinary text without R code

  |...............................................                       |  67%
label: unnamed-chunk-1
  |......................................................................| 100%
  ordinary text without R code


output file: read_me.knit.md

pandoc 
  to: gfm+footnotes+tex_math_dollars-yaml_metadata_block
  output-file: /Users/MJ/GitHub/testing_quarto_in_r/README.md
  standalone: true
  default-image-extension: png
  
metadata
  editor: visual
  
ERROR: NotFound: No such file or directory (os error 2)
```

However, if any one of the R chunk, `output-file`, or `_quarto.yml` is removed, the Quarto document will render just fine. 

I put together a [small test repository](https://github.com/MCMaurer/testing_quarto_in_r) that contains 3 Quarto docs with various combinations of these factors to demonstrate the error.

I'm running this with the latest versions of R, RStudio, and Quarto, on MacOS Monterey 12.4.

**Comment by cderv** [comment]
Sorry for the delay on this. This is the issue thread of the R Package quarto, and we are not thoroughly following as we do for the main project at [quarto-dev/quarto-cli](https://github.com/quarto-dev/quarto-cli/)

I did try your test repository and can't reproduce with latest versions of the tools. 

if you still have issue please do open in a main repo. 

Thank you
