### ISSUE TITLE
Quarto won't compile document containing string `r ** 2`

### ISSUE THREAD

**Issue by yoctobug** [quarto-dev/quarto-r#40]
File containing string `r ** 2` fails to compile. File containing string `s ** 2` renders A-OK

```
$ echo '`r ** 2`' > mre.qmd

~/bug                                                                                    
$ quarto render mre.qmd
Error in loadNamespace(x) : there is no package called ‘jsonlite’
Calls: .main ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted

R installation:
  Version: 4.2.1
  Path: /usr/local/Cellar/r/4.2.1/lib/R
  LibPaths:
    - /usr/local/lib/R/4.2/site-library
    - /usr/local/Cellar/r/4.2.1/lib/R/library
  rmarkdown: (None)

The rmarkdown package is not available in this R installation.
Install with install.packages("rmarkdown")


~/bug                                                                                   ⍉
$ echo '`s ** 2`' > ok.qmd

~/bug                                                                                    
$ quarto render ok.qmd 
pandoc 
  to: html
  output-file: ok.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  
Output created: ok.html
```

**Comment by cderv** [comment]
Sorry for the delay here. This is the issue thread of the R Package quarto, and we are not thoroughly following as we do for the main project at [quarto-dev/quarto-cli](https://github.com/quarto-dev/quarto-cli/)

Using R with Quarto requires some setup, especially the **rmarkdown** package to be installed.
https://quarto.org/docs/computations/r.html#installation

> The rmarkdown package is not available in this R installation.
Install with install.packages("rmarkdown")

here it seems you don't have the required package installed in your setup

**Comment by yoctobug** [comment]
Should I report this to quarto-dev/quarto-cli?

**Comment by cderv** [comment]
By doing this 
````
 echo '`r ** 2`' > mre.qmd
````
you are inserting syntax for a inline R expression. https://quarto.org/docs/computations/execution-options.html#knitr

I believe here you want just a inline code in markdown - that is unfortunate. It seems a document with only this is automatically seen as a document using R code. This does not seem right. It should at least be an R chunk maybe. 

This specific behavior will only happen with this special syntax, any other should not trigger any R if you don't use R at all.

It seems like our engine binding should be improved. You can however configure manually and force a behavior; 
https://quarto.org/docs/computations/execution-options.html#engine-binding

Sorry for the trouble. i'll open an issue for that in Quarto cli repo.

**Comment by yoctobug** [comment]
OK. Understood. In the original source document that brought this to my attention, I was trying to use inline `code` within a paragraph of plaintext in a .qmd file. After some tinkering, I found that `r... was the culprit. Using any other letter (as indicated above) works just fine. Thanks.
