### ISSUE TITLE
{} dropped on some divs when switching between source and visual editor

### ISSUE THREAD

**Issue by carobuck** [quarto-dev/quarto-r#41]
When switching from source to visual editor, then back again to source, some of the formatting is dropped on some div chunks.

e.g.  after all the switches, the speaker notes div is shown as:
::: notes

rather than
::: {.notes}

I have noticed the dropping of . and {} for .notes, some .fragments and .footer div sections (if additional parameters are in the div chunk, e.g. column width or fragment display types, the {} tend to stay).

Sometimes, missing the {.} has messed up subsequent chunks for me, where they are not formatted correctly/corresponding to their div type (indicated by what would be in {})

**Comment by bhogan-mitre** [comment]
I noticed this as well and I've been wondering if it was an issue with the quarto version, the RStudio IDE version, or something else.  Regardless, this seems related to some issues in the `quarto-cli` repo such as https://github.com/quarto-dev/quarto-cli/issues/2522
