### ISSUE TITLE
Feature request: Add the equivalent of `rmarkdown::draft()` to this package

### ISSUE THREAD

**Issue by remlapmot** [quarto-dev/quarto-r#42]
I tried to include a *skeleton.qmd* file as a skeleton file in an R package like I would with a *skeleton.Rmd* file. 

Unfortunately, for the package user `rmarkdown::draft()` doesn't behave as expected because the *skeleton.Rmd* filename is hardcoded [here](https://github.com/rstudio/rmarkdown/blob/63b7ecf5e4672a6dacef7e5899c479e6e4080052/R/draft.R#L125). All the files from the skeleton directory are copied but the *skeleton.qmd* file is not renamed.

An example is as follows.
``` r
remotes::install_github("remlapmot/mytestpackage", quiet = TRUE)
rmarkdown::draft("example.qmd", template = "quarto_template", package = "mytestpackage", edit = FALSE)
#> Warning in file.rename(file.path(dirname(file), "skeleton.Rmd"), file): cannot
#> rename file 'example/skeleton.Rmd' to 'example/example.Rmd', reason 'The system
#> cannot find the file specified'
dir("example")
#> [1] "skeleton.qmd"
```

<sup>Created on 2022-08-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Is there different advice how to include Quarto templates in R packages, or would you add the equivalent of `rmarkdown::draft()` to this package, or maybe allow `rmarkdown::draft()` to accept *skeleton.qmd* files?

**Comment by cderv** [comment]
Related discussion topic: https://github.com/quarto-dev/quarto-cli/discussions/4413
