### ISSUE TITLE
fig-width and fig-height visualization outside of rendering

### ISSUE THREAD

**Issue by nick-youngblut** [quarto-dev/quarto-r#44]
One generally first plots via the interactive editor, iteratively running each cell block. However, the following does nothing to change the plot size produced in either `source` or visual` mode in Rstudio:

```{r}
#| fig-width: 
#| fig-height: 
```

How is one supposed determine the "optimal" width/height to visualize the figure (e.g., a large faceted figure) without constantly rendering the entire document or using both  `#| fig-*` and `{r, fig.width=X, fig.height=X}` for each plot, which is overly cumbersome code, especially with a lot of figures?

I'm using quarto 1.0.36.

**Comment by nick-youngblut** [comment]
I guess that one can just stick with `{r, fig.width=X, fig.height=X}` and not use `#| fig-*`, but it would be helpful to point this fact out in the Quarto docs.

**Comment by nick-youngblut** [comment]
Getting the figures all in an "optimal" size seems to be even more of a challenge when plotly is involved

**Comment by cderv** [comment]
Sorry for the delay on this. This is the issue thread of the R package and we don't thoroughly follow it as we do for the main project at https://github.com/quarto-dev/quarto-cli/

If you still have issue with latest version of tools (Quarto and RStudio), please do open a new issue there. 

Thank you !
