### ISSUE TITLE
LaTeX \newcommand doesn't work in HTML doc

### ISSUE THREAD

**Issue by friendly** [quarto-dev/quarto-r#46]
In a Quarto document, I want to be able to use more extensive math LaTeX features than are typical for simple equations, using some extensions presumably provided by mathjax, particularly for matrix expressions.

However, I find that some mathjax features just do not work as documented. In particular, the use of `\newcommand`, `\renewcommand`, etc. do not work.

I created a .qmd file to test this, published on [Rpubs: https://rpubs.com/friendly/test-newcommand](https://rpubs.com/friendly/test-newcommand).

This uses the following to define some new latex commands:

    ::: {.hidden}
    $$
    \renewcommand*{\vec}[1]{\mathbf{#1}} 
    \newcommand*{\mat}[1]{\mathbf{#1}} 
    \newcommand{\trans}{^\mathsf{T}} 
    \newcommand*{\diag}[1]{\mathrm{diag}\, #1}}
    \newcommand{\sizedmat}[2]{\underset{\mathbf{#1}}{(#2)}}
    $$

Then this is used as:

    $$
    {\sizedmat{\mat{Y}}{n \times p}} = 
    {\sizedmat{\mat{X}}{n \times q}} \, 
    {\sizedmat{\mat{B}}{q \times p}} + 
    {\sizedmat{\mat{U}}{n \times p}} ,
    $$

 But the result appears in the HTML output as shown in this image:

![sizedmat](https://user-images.githubusercontent.com/456353/184921374-104fbf50-a771-4f78-ab63-0f17b6e39921.png)

**Comment by friendly** [comment]
Perhaps I shouldn't have raised this as an issue with `quarto-r`.  There is some discussion of this on `quarto-cli`, https://github.com/quarto-dev/quarto-cli/discussions/1793

**Comment by mcanouil** [comment]
This is more of a Quarto/Pandoc question/issue rather than something related to the R package which is only a wrapper to Quarto.

You might want to take a look at https://github.com/quarto-dev/quarto-cli/discussions/2068

**Comment by friendly** [comment]
Closing this as more related to `quarto-dev/quarto-cli`
