### ISSUE TITLE
Could one pass the "lang" parameter via quarto_render?

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-r#49]
Related to https://github.com/quarto-dev/quarto-cli/issues/275

I'd like to use a single Quarto configuration file for books in two different languages.
I can edit it via an orchestration script but I wonder whether one could override what's in the configuration file via an argument of `quarto_render()`?

**Comment by mcanouil** [comment]
Maybe as Pandoc with `--metadata-file=FILE` (<https://pandoc.org/MANUAL.html>) 🤔.

**Comment by maelle** [comment]
:tada: merci @mcanouil @cderv

**Comment by cderv** [comment]
Hopefully this will work as expected. Keep me updated. I know we have some side effect in quarto itself
* https://github.com/quarto-dev/quarto-cli/issues/6123

**Comment by joelnitta** [comment]
@maelle what about using a [project profile](https://quarto.org/docs/projects/profiles.html)?
