### ISSUE TITLE
Quarto presentation with space in filename

### ISSUE THREAD

**Issue by mintzj** [quarto-dev/quarto-r#50]
A Quarto presentation in Rstudio created with a space in the filename doesn't render correctly in Windows.  It produces the following error in the background jobs pane:

> 'C:/Program' is not recognized as an internal or external command,
> operable program or batch file.

When the space is replaced by an underscore, the file will render.  The filenames I tested were "demo script.Qmd", which does not render, vs "demo_script.Qmd", which renders.  The file I tried to render was the basic template for a revealJS presentation.

Sorry if this is not the correct place to post this issue, Quarto seems to have lots of pieces and I am not sure what is causing this to break.

**Comment by cderv** [comment]
This could be an issue in RStudio IDE which is already reported in https://github.com/rstudio/rstudio/issues/11804 and https://github.com/rstudio/rstudio/issues/11779

Also it was already reported in Quarto CLI repo https://github.com/quarto-dev/quarto-cli/issues/1998

I'll close this here and you can follow up on there. 

Thanks for the report
