### ISSUE TITLE
Can I render a .html and a .pdf presentation in the same .qmd with format: revealjs?

### ISSUE THREAD

**Issue by rtheodoro** [quarto-dev/quarto-r#51]
I have been working with Quarto in RStudio to do some presentations.

I like to do the presentations with `format: revealjs` and than convert the `.html` output to .pdf to send to my students.

Can I render both formats at the same time?

```r
---
title: "R and RStudio"
author: "RTheodoro"
institute: "USP"
format: 
   revealjs:
     logo: img/usp_logo.png
     slide-number: true
     show-slide-number: all
     preview-links: auto
     width: 1280
     height: 720
     theme: default
editor: visual
execute:
  echo: true
---

## What is R?

-   R is.....
```

**Comment by mcanouil** [comment]
No you can't, but you could use [`webshot2`](https://rstudio.github.io/webshot2/) R package or [`renderthis`](https://jhelvy.github.io/renderthis/).
With the former, you will have to write a script/function to go through the slides, while the latter was mostly designed to work with `xaringan` (Remark.js) slides, thus might not work as expected for Reveal.js HTML document.

Finally, there is the manual solution of what `webshot2` is doing, i.e., opening the HTML in a chromium based browser and use the print to pdf option.

**Comment by cderv** [comment]
I think there is simpler version of that if what you are looking is manually printing to PDF your slide. The revealjs format offers a print ready version of the slide. See https://quarto.org/docs/presentations/revealjs/presenting.html#print-to-pdf

Some options can be configured to tweak a bit the print ready version. 

This is based on HTML + CSS only so if you want to automate you can just use the url of the slide for the print ready version and then use a tool like **webshot2** or R Markdown ecosystem function link `pagedown::chrome_print` to do the Chrome printing but using code (which you can then automate). 

Hope it helps.

**Comment by remlapmot** [comment]
thanks indeed - very helpful. A little R script of
```r
# install.packages("quarto")
# install.packages("pagedown")
quarto::quarto_render("myslides.qmd")
pagedown::chrome_print("myslides.html")
```
output *myslides.pdf* with 1 page per slide, which was good enough for me.

**Comment by cderv** [comment]
If you want a better result, you should consider using the PDF export mode. You can access the url with the IDE button or within the slide "e" keyboard shortcut. This should add a `?print-pdf` at the end of your url. 

This would mean rendering, then serving the slide, then printing 😅 

I don't think pagedown would do that for you. Or it supports this special url. I need to check. 

Maybe I should add a print function version in the R package based on **pagedown** that would know about that 🤔  ?

**Comment by cderv** [comment]
> I don't think pagedown would do that for you. Or it supports this special url. I need to check.

Oh in fact we are currently doing  that correctly ! 

So yes 
````
quarto::quarto_render("myslides.qmd")
pagedown::chrome_print("myslides.html")
````

this works fine!

**Comment by rtheodoro** [comment]
Thanks a lot for your help, guys!

> Maybe I should add a print function version in the R package based on **pagedown** that would know about that thinking ?

I think it would be nice! Thanks again!
