### ISSUE TITLE
render fails with non-default `output_file`

### ISSUE THREAD

**Issue by qiushiyan** [quarto-dev/quarto-r#54]
When I set `output_file` in `quarto::quarto_render()`, the function fails. This happens no matter `output_file` preexists or not. 

``` r
lines <- c(
  "---",
  "title: 'test'",
  "format: html",
  "---"
)

f <- tempfile(fileext = ".qmd")
writeLines(lines, f)
quarto::quarto_render(f)
#> [1mpandoc [22m
#>   to: html
#>   output-file: file8f826c66ae57.html
#>   standalone: true
#>   section-divs: true
#>   html-math-method: mathjax
#>   wrap: none
#>   default-image-extension: png
#>   
#> [1mmetadata[22m
#>   document-css: false
#>   link-citations: true
#>   date-format: long
#>   lang: en
#>   title: test
#>   
#> Output created: file8f826c66ae57.html
quarto::quarto_render(f, output_file = "test.html")
#> [1mpandoc --output ../../../../../../private/var/folders/r2/ycy8hp_54yd7bxc_0kyb5trm0000gn/T/RtmpJSZSyR/reprex-8e845d74fc79-super-sable/test.html[22m
#>   to: html
#>   standalone: true
#>   section-divs: true
#>   html-math-method: mathjax
#>   wrap: none
#>   default-image-extension: png
#>   
#> [1mmetadata[22m
#>   document-css: false
#>   link-citations: true
#>   date-format: long
#>   lang: en
#>   title: test
#>   
#> pandoc: ../../../../../../private/var/folders/r2/ycy8hp_54yd7bxc_0kyb5trm0000gn/T/RtmpJSZSyR/reprex-8e845d74fc79-super-sable/test.html: openFile: does not exist (No such file or directory)
#> Error in "processx::run(quarto_bin, args, echo = TRUE)": ! System command 'quarto' failed
```

<sup>Created on 2022-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

package and quarto version 

``` r
packageVersion("quarto")
#> [1] '1.2.0.9000'

processx::run("quarto", c("--version"))$stdout
#> [1] "1.1.132\n"
```

<sup>Created on 2022-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by qiushiyan** [comment]
seems duplicate of #43

**Comment by lawalter** [comment]
Hi @qiushiyan, have you tried rendering without the ".html" suffix? For example if you try running with `output_file = "test"` it should work.

**Comment by qiushiyan** [comment]
@lawalter Thanks for the suggestion, but removing the file extension did not work for me.

@cderv I updated quartor two use the github dev version, now the two outputs are 

```r
> quarto::quarto_path()
[1] "/usr/local/bin/quarto"
> quarto::quarto_version()
[1] ‘1.2.335’
```

**Comment by cderv** [comment]
> Error in "processx::run(quarto_bin, args, echo = TRUE)": ! System command 'quarto' failed

It seems there is indeed an issue finding quarto. Let's run some more check if you're ok. 

`quarto:::find_quarto()` will be the path of the Quarto run by `processx::run()` 	- it should be identical to `quarto_path()` above. 

This means that from what you've shared above `"/usr/local/bin/quarto"` should be used. Can you run quarto at command line without R package ? Either from PATH `quarto check` or directly the one supposed to be used `/usr/local/bin/quarto check` ? 

Thanks

**Comment by cderv** [comment]
> ```
> #> pandoc: ../../../../../../private/var/folders/r2/ycy8hp_54yd7bxc_0kyb5trm0000gn/T/Rtmp3xQWn6/reprex-90d751de7622-cocky-doe/test: openFile: does not exist (No such file or directory)
> #> Error in "processx::run(quarto_bin, args, echo = TRUE)": ! System command 'quarto' failed
> ```

Thanks a lot, it seems that the command line is correctly found but there is an issue somehow in a file path. 

I see `reprex` in there. Did you run the above code using **reprex** R package to share ? 
Is this failing exactly the same if you run in your console the R command only (not within a reprex) ? 
I really don't know how reprex will behave to run example using a quarto conversion. I think it may not work at all. 
Anyway, just want to check the error you have otherwise, without using **reprex**

This is because I cannot reproduce an issue but I can see a maybe a specific behavior. 

When setting `output_file`, the file path used will be relative to your working directory and not the input file directory. So in your example, input is in temp folder, but output will be in your current working directory. This works for me, is it for you ? 
````r
> f <- tempfile(fileext = ".qmd")
> writeLines(lines, f)
> quarto::quarto_render(f, output_file = "test.html")
pandoc --output ..\..\..\..\Documents\test.html
  to: html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: test
  
Output created: ..\..\..\..\Documents\test.html
````


Thank youy

**Comment by qiushiyan** [comment]
> When setting output_file, the file path used will be relative to your working directory and not the input file directory. So in your example, input is in temp folder, but output will be in your current working directory. This works for me, is it for you?

This does not work for me. The error is the same when runnning without reprex: `pandoc: ../Users/xxx/test.html: openFile: does not exist (No such file or directory))`

**Comment by cderv** [comment]
Thanks for the feedback. Is this with latest 1.2.335 ? 

We have prerelease 1.3 available can you try that ? 

Maybe we fixed something related to this and this would explain why it works for me.

**Comment by qiushiyan** [comment]
1.3 does not help :(

```r
> quarto::quarto_version()
[1] ‘1.3.178’
> f <- tempfile(fileext = ".qmd")
> writeLines(lines, f)
> quarto::quarto_render(f, output_file = "test")
pandoc --output ../../../../../../Users/qiushi/workspace/dsi-courses/DS1000_S2023/test
  to: html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  title: test
  
pandoc: ../../../../../../Users/qiushi/workspace/dsi-courses/DS1000_S2023/test: openFile: does not exist (No such file or directory)
Error in `processx::run(quarto_bin, args, echo = TRUE)`:
! System command 'quarto' failed
---
Exit status: 1
stdout & stderr: <printed>
---
```

**Comment by cderv** [comment]
Can you share what `f` is ? Where is your temp file ? 

it feels something OS specific, like cross directory structure somehow. Issue is not that helpful unfortunately. 

You could try using `quarto` at command line without passing by R to call it. And also set traceback 
https://quarto.org/bug-reports.html#dont-hold-back-tell-us-anything-you-think-might-make-a-difference

**Comment by qiushiyan** [comment]
`f` is at `"/var/folders/r2/ycy8hp_54yd7bxc_0kyb5trm0000gn/T//RtmpqKAZ7l/file1672d78693b85.qmd"`

I found that both the command line and R function will support `--output` if the file is not in the temp directory. So if `f` is "test.qmd", it will work.

**Comment by cderv** [comment]
> f is at "/var/folders/r2/ycy8hp_54yd7bxc_0kyb5trm0000gn/T//RtmpqKAZ7l/file1672d78693b85.qmd"

Thanks for sharing that. It helps. The file is in another "mount": 
- `f` is in `/var/folder` 
- input document `Users/qiushi/workspace` probably not in `/var` filesystem. 

I think this is directly to https://github.com/quarto-dev/quarto-cli/issues/3992 - This create issue in the way all this works. especially with what Pandoc expects. 

See my comment there: https://github.com/quarto-dev/quarto-cli/issues/3992#issuecomment-1385176127

I believe this is a duplicated and I did not see that before. so we probably should continue there then.

**Comment by qiushiyan** [comment]
Thanks for all the help. I'll close this and follow the issue you mentioned.
