### ISSUE TITLE
How to load automatically during quatro_render .Renviron/.Rprofile/Rprofile-site/Renviron-site?

### ISSUE THREAD

**Issue by avraam-inside** [quarto-dev/quarto-r#64]
Previously, this feature was removed in rmarkdown, and it doesn't work in quatro either.

Could you bring this setting to a certain option, please? (preferably in the title section of the qmd file)

**Comment by mcanouil** [comment]
Does the issue also appear when using Quarto CLI directly?

**Comment by cderv** [comment]
> Previously, this feature was removed in rmarkdown,

I am not sure what you are referring too. All the startup R files are run by your R process independently of **rmarkdown** behavior. If you call `rmarkdown::render()` in your current seesion, those files have already been executed. If you run in another R session from your terminal, they will also get executed unless some specific option have been passed to R. 

Anyway, this is not specific to R Markdown or Quarto. This is R behavior and those files will be executed with Quarto also as `quarto render` will start a R session as part of the process. Some tools like **renv** rely on this and works well with Quarto https://quarto.org/docs/projects/virtual-environments.html#using-renv

If this is not working as expected for you, please asked for help in Q&A site, or directly in Quarto Discussion https://github.com/quarto-dev/quarto-cli/discussions

> Could you bring this setting to a certain option, please? (preferably in the title section of the qmd file)

Before asking to add something that you think is missing, it is good practice to contribute some details to the discussion with examples, what is working and what is not. It is helpful for others to understand what's working or not. 

Thank you.
