### ISSUE TITLE
YAML Front Matter Code Blocks Tweaks

### ISSUE THREAD

**Issue by Sang-Buster** [quarto-dev/quarto-r#68]
Inside `.qmd`'s YAML front-matter. If I set `code-fold: true`, the `code-tools` would work just fine, but if I set `code-fold: false`, I can no longer toggle the `code-tools` in particular the code folding and showing button is no longer there, it would just pop up a source code page.

**Comment by mcanouil** [comment]
Please report this with a reproducible example to the proper repository <https://github.com/quarto-dev/quarto-cli>.
This repository is about the Quarto R wrapper, not Quarto itself. 😉

**Comment by Sang-Buster** [comment]
I see, thanks!
