### ISSUE TITLE
Quarto fails to render Chinese characters  in PDF  from A Quarto Book Project created from RStudio)

### ISSUE THREAD

**Issue by LANCECN** [quarto-dev/quarto-r#69]
The Chinese characters can be rendered correctly in HTML format, but  not in PDF format.  
RStudio,  
Quarto Book,  
pdf-engine:   xelatex

it's a bug? or I missed some settings? Any suggestions?   Thanks a lot.

**Comment by hashiromer** [comment]
I am running into the same problem. How did you resolve it?
