### ISSUE TITLE
RStudio doesn't preview Quarto PDF document properly when changing font

### ISSUE THREAD

**Issue by maxdrohde** [quarto-dev/quarto-r#7]
Apologies if this is not the right place to submit this issue -- let me know and I can move it.

When rendering a Quarto document to PDF in RStudio, it works fine with the regular settings. However, when I change the font of the PDF document, the RStudio PDF viewer doesn't render the document properly.

The document itself is normal when viewed in another PDF viewer, like Preview on Mac. See below screenshots.

## Version Info
RStudio 2022.02.0 Build 431
Quarto 0.9.7
MacOS Monterey 12.1

## View in RStudio
<img width="770" alt="Screen Shot 2022-02-11 at 13 32 54" src="https://user-images.githubusercontent.com/25734232/153658180-338a7f42-1d14-4ac3-8d85-4b6fdb980e93.png">

## View in Preview on Mac
<img width="774" alt="Screen Shot 2022-02-11 at 13 33 20" src="https://user-images.githubusercontent.com/25734232/153658240-1f9a208e-49f5-4ff4-840e-7c8fb3658460.png">

## Source code of `.qmd` file

```
---
title: "pdf_test"
format:
  pdf:
    mainfont: Times New Roman
---

Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.

Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.

But, in a larger sense, we can not dedicate -- we can not consecrate -- we can not hallow -- this ground. The brave men, living and dead, who struggled here, have consecrated it, far above our poor power to add or detract. The world will little note, nor long remember what we say here, but it can never forget what they did here. It is for us the living, rather, to be dedicated here to the unfinished work which they who fought here have thus far so nobly advanced. It is rather for us to be here dedicated to the great task remaining before us -- that from these honored dead we take increased devotion to that cause for which they gave the last full measure of devotion -- that we here highly resolve that these dead shall not have died in vain -- that this nation, under God, shall have a new birth of freedom -- and that government of the people, by the people, for the people, shall not perish from the earth.

```

**Comment by cderv** [comment]
This has been opened in RStudio IDE repo so I am closing here. Thanks
