### ISSUE TITLE
Presentation view does not update automatically.

### ISSUE THREAD

**Issue by piiskop** [quarto-dev/quarto-r#71]
This anomaly occurs in _RStudio Server_. i had created a QMD-file inside a subfolder that was inside a subfolder. Testing via _Render_ was no problem. Suddenly rendering did not work anymore and instead of a rendered presentation a rendered webpage was displayed in _Presentation_ view.

i created a test file and that was rendered fine. i even copied and pasted the content of the test file into the first-mentioned file and rendering did not work. In _Jobs_:

> Watching files for changes

>  /presentation_files/libs/revealjs/dist/reset.css (404: Not Found)
>  /presentation_files/libs/revealjs/dist/reveal.css (404: Not Found)
>  /presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css (404: Not Found)

These files are all there, i mean in the subfolder of the subfolder.

Renaming the file made rendering work correctly however _Presentation_ view would not show any changes inside the file afterward.

**Comment by mcanouil** [comment]
This is not an issue with the R package.
Please provide a reproducible example, describe the tools (and their version) you are using and report this to <https://github.com/quarto-dev/quarto-cli>.
