### ISSUE TITLE
Chunk output of data frame summary functions too cramped

### ISSUE THREAD

**Issue by MokeEire** [quarto-dev/quarto-r#75]
When using functions like `summary()` or `dplyr::glimpse()` in a Quarto document, the output is regularly too cramped to read clearly.

Example:
```
summary(mtcars)
```

![image](https://user-images.githubusercontent.com/19700454/202563591-6fff1b16-b431-44d6-b53b-efd066ee4abd.png)

```
dplyr::glimpse(mtcars)
```

![image](https://user-images.githubusercontent.com/19700454/202563743-0f51922f-507f-425b-81a7-e97a5a44de76.png)

Using the `width` argument with `glimpse()` is a viable workaround but it would be much nicer if the default output fit.

**Comment by mcanouil** [comment]
Your screenshots seems to come from an IDE and not the Quarto document itself, nor Quarto.
This should be reported on the repository of the IDE.
Also, what you are reporting is tied to knitr, and especially R. This is the default "width" option in R.
You can change it in your `.Rprofile` to make it "general".

**Comment by cderv** [comment]
I confirm this is not an issue with Quarto itself. I can be solved using configuration on packages used, and maybe improve the knitr output. This will then work in Quarto.
