### ISSUE TITLE
Passing params to Shiny "context: server" code chunks

### ISSUE THREAD

**Issue by gacolitti** [quarto-dev/quarto-r#78]
As explained [in this stackoverflow post](https://stackoverflow.com/questions/74463675/passing-params-to-shiny-server-context-in-quarto), Knitr params are not passed to `context: server` code chunks when using a Shiny backend. 

Here is a reprex:

````
---
title: "test"
format: html
server: shiny
params:
  test: "test"
---

```{r}

shiny::verbatimTextOutput("test")
```

```{r}
#| context: server

output$test <- shiny::renderText(params$test)

```
````

**Comment by cderv** [comment]
This is not a quarto specific issue, but rather a limitation on how shiny prerendered document works (both in R Markdown and in Quarto)

The detailed explanation can be found in https://quarto.org/docs/interactive/shiny/execution.html

> Shiny interactive documents can contain both code that executes at render time as well as code that executes on the server in response to user actions and changes in input values. A solid understanding of these execution contexts is important both to have the right mental model during development as well as to optimize the performance of your document.

Basically, the UI part of the document and the server part of the document will be run in two separate process. So the server context won't know about params unless it is somehow pass to it explicitly, or what you do with the parameters end up having existence in server part. It is like in shiny between what you do in UI and Server - both are separate functions. 

Then, params is quite specific as it will be known and handle during the knitting phase only. This means during the UI rendering part of the shiny app. `params` won't be found during the rendering of the server context, even when trying to be passed in a shared context (data or setup). 

Using parametrized feature with shiny execution is not possible easily, without passing information to disk for example. Parameters lost there flexibility in this case. 

Hope it helps understand.
