### ISSUE TITLE
Asides don't seem to work

### ISSUE THREAD

**Issue by akgold** [quarto-dev/quarto-r#8]
I wanted to add an aside comment, as documented here: https://quarto.org/docs/authoring/article-layout.html

Putting the document below into a `.qmd` and rendering (using `cmd + shift + k`) in the RStudio IDE (2022.02.0 Build 435.pro1) yields all of the text in the body of the doc, not the margin.

```
---
title: "Untitled"
format: html
editor: visual
---
# My Test Doc

Test 
[Go in the margin?]{.aside}


::: {.column-margin}
We know from *the first fundamental theorem of calculus* that for $x$ in $[a, b]$:

$$\frac{d}{dx}\left( \int_{a}^{x} f(u)\,du\right)=f(x).$$
:::
``` 

## Screenshot of rendered doc
<img width="606" alt="image" src="https://user-images.githubusercontent.com/394930/157080773-b81cb3b7-1fdd-4136-907e-7529cc59a671.png">

**Comment by dragonstyle** [comment]
Hmmm. I just gave this example a quick test run locally and all seems to be working. I have a couple of thoughts:

1) It is possible if the preview window is narrow enough, the aside content will return into the body of the document where it was originally positioned (we do this so in mobile and other form factors, the document remains usable).

2) If that isn't the issue, would you mind viewing the source of the rendered document and shared the `generator` `meta` tag value. This will be the quarto version that is rendering the document and may provide a clue as well, if for example it an older version of Quarto that didn't have aside support yet...

Sorry for the issue!

**Comment by akgold** [comment]
Aha -- it was the preview window width 🤦🏻 

I'm trying to think of any way this could've been more obvious, but definitely seems like this one is on me. 

Sorry for the bother.

**Comment by dragonstyle** [comment]
No worries at all, glad it was an easy one!

**Comment by PhilipPMolloy** [comment]
> Aha -- it was the preview window width 🤦🏻
> 
> I'm trying to think of any way this could've been more obvious, but definitely seems like this one is on me.
> 
> Sorry for the bother.

If it makes you feel any better, I just had the same issue happen to me, and your post solved it for me. So thanks!
