### ISSUE TITLE
`Knit` pdf doesn't work

### ISSUE THREAD

**Issue by dklinenberg2020** [quarto-dev/quarto-r#83]
I try and knit my .qmd file to pdf and get the following error:

> compilation failed- package installation error
I can't find file `pgfkeyslibraryfiltered.code.tex'.
l.1230 \input pgfkeyslibraryfiltered.code.tex

The file is located at `~library/tinytex/texmf-dist/tex/generic/pgf/utilities/pgfkeyslibraryfiltered.code.tex` with all the other docs.

I've tried redownloading Rstudio and tinytex to no avail. Any advice?

I'm working on a Mac with an M1 chip.

**Comment by cderv** [comment]
> I try and knit my .qmd file to pdf 

Why do you mean by "Knit" ? Did you run `knitr::knit()` on it ? Or `quarto::quarto_render()` ? 
How did you render to PDF ? 

> \input pgfkeyslibraryfiltered.code.tex

Is this in your Qmd file ? Can you share your qmd file content ? 


Just trying to understand what you are trying to do and so what could be the issue, where it could be. 

If you can provide a reproducible examples, or steps to make one on my side, that would help. More information is needed.
