### ISSUE TITLE
knitr params specified in project profile ignored

### ISSUE THREAD

**Issue by gacolitti** [quarto-dev/quarto-r#84]
Here is a quarto document that prints out a knitr param value:

```
---
title: "test-quarto-profiles-static"
format: html
---

`r params$val`
```

Here is a `_quarto.yml` project profile file in the project root directory:

```
project:
  title: "test-quarto-profiles"
params:
  val: false
```

I expect `params$val`  to be printed out, but instead I get an error: ``object `params` not found``

----

I also tried specifying Knitr params using the quarto CLI [described here](https://quarto.org/docs/computations/parameters.html#rendering):

```
quarto render doc.qmd -P val:true
```

but I get the same error.

----

How do I pass kintr params via profiles? 

The goal is to list default params in the `_quarto.yml` file and create more profiles like `_quarto-profile1.yml` and `_quarto-profile2.yml` that can be selectively called to update the default params set in `_quarto.yml`.

**Comment by gacolitti** [comment]
If I add `params` to the top of the doc.qmd like this:
```
params:
  val: true
```

then render with:

```
quarto render doc.qmd -P val:false
```

I get the expected output.

But I'm still not sure how to pass params in a `_quarto.yml` and the `-P` argument to `quarto render` does not work with `quarto serve` for Shiny apps.

**Comment by gacolitti** [comment]
Okay, looks like you can render the HTML file and pass params, then serve the Shiny app with HTML without rerendering:

```
quarto render doc.qmd -P val:false
```

then

```
quarto serve doc.qmd --no-render
```

This seems like an okay workaround, but I'm not sure there is a way to publish to Posit Connect using this method. It seems that once deployed to Posit Connect the HTML file will be rerendered even if you upload the locally rendered HTML file.

**Comment by gacolitti** [comment]
Adding `freeze: true` to `_quarto.yml` and uploading to Posit Connect solves the issue of rerendering when deployed to Posit Connect.

**Comment by cderv** [comment]
We don't currently support params at project level. See https://github.com/quarto-dev/quarto-cli/issues/864 for current feature request

For now, params needs to be defined and set at the document level, and then each document render using command line or default value. 

it seems you manage to do what you wanted so I'll close this, and you can follow the other issue
