### ISSUE TITLE
(aarch64 / arm64): Let Deno install from source

### ISSUE THREAD

**Issue by ninohardt** [quarto-dev/quarto-r#85]
Feature request: Allow Deno from source installation instead of expecting binaries. Deno does not have official binaries for aarch64, but it compiles fine from source.

**Comment by dragonstyle** [comment]
We do allow the override of our built in Deno path using the environment variable `QUARTO_DENO`. We bind to specific versions of Deno and the std libraries, so if you elect to use this definitely stick to that version and YMMV.
