### ISSUE TITLE
quarto create wrapper

### ISSUE THREAD

**Issue by maelle** [quarto-dev/quarto-r#87]
Would a function for for instance

```r
quarto create-project mybook --type book
```

be in scope?

My use case is creating a function that creates a Quarto book (for testing code that will translate it), which is why I am not using the RStudio interface.

**Comment by davidkane9** [comment]
I second this request, but for creating Quarto websites.

**Comment by see24** [comment]
It would also be nice if there were usethis like functions for add a chapter, or add appendix or other situations where some boilerplate needs to be added to the _quarto.yml and then you need to create a new .qmd with the same title. 

eg:
`add_chapter(name, .before, .after)` could add  name.qmd to the _quarto.yml file at the end of existing chapters or optionally before or after an existing one and then create and open name.qmd.

**Comment by cderv** [comment]
Please try current dev version. I added support for calling `quarto_create_project()`. it should ask for confirmation interactively, but you can opt-out for usage in a script workflow.
