### ISSUE TITLE
does this package update together with quarto-cli?

### ISSUE THREAD

**Issue by sbalci** [quarto-dev/quarto-r#9]
Hi,

Does this package update together with quarto-cli?

When one runs `quarto::quarto_render(".")` does it work on the R-package version or CLI version?

Thank you

**Comment by salim-b** [comment]
It does nothing alike. It's a simple wrapper around the CLI which must be installed separately. From the DESCRIPTION file:

https://github.com/quarto-dev/quarto-r/blob/e096f7d3b213fba24f13020464e56c3f91051204/DESCRIPTION#L14

Or to answer your question

> When one runs quarto::quarto_render(".") does it work on the R-package version or CLI version?

It uses the CLI version, there is no "R-package version" of Quarto.

**Comment by sbalci** [comment]
Thank you for the clarification 👍🏼

**Comment by cderv** [comment]
Thank you @salim-b !
