### ISSUE TITLE
Feature request: sidebar footnotes

### ISSUE THREAD

**Issue by P-Courtney** [quarto-dev/quarto-r#93]
With screens wider than long, it makes sense to have footnotes as close to the text as possible, i.e. in a sidebar on the right. See here for an elegant implementation: https://asteriskmag.com/issues/2/the-virtue-of-wonder-martha-nussbaum-s-justice-for-animals

**Comment by dragonstyle** [comment]
This should be supported currently- see:

https://quarto.org/docs/authoring/article-layout.html#margin-references
