### ISSUE TITLE
`quarto_render()` [WARNING] Could not fetch resource 

### ISSUE THREAD

**Issue by asadow** [quarto-dev/quarto-r#99]
With Quarto 1.3.333 on Windows 11, I get the same "[WARNING] Could not fetch resource" as the below posting but when running something like `quarto_render(input = "qmd/blah.qmd", output_file = X)`.

Interestingly the warnings and lack of formatting resolve if I simply move `blah.qmd` to the project root folder and set the `input` argument to match.

Could be related to @bryanwhiting in https://github.com/quarto-dev/quarto-cli/discussions/4041_

**Comment by cderv** [comment]
Are the warning coming from quarto execution ? Probably so, I think nothing to do with the R package. 
Does `quarto render` throw also the warnings ? 

FWIW I can't reproduce this on my side with simple document. Do you have a content example to share ?  Maybe it is coming from a specific configuration or organisation.

**Comment by asadow** [comment]
You're correct; the same warnings are thrown by quarto render. I can see this progressed to [this discussion](https://github.com/quarto-dev/quarto-cli/issues/5765)
